sonar.projectKey=0x524a_rtspeek
sonar.organization=0x524a

sonar.sources=.
sonar.exclusions=bin/**,coverage.out

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
